# Generated by Django 5.1.4 on 2026-04-17 02:21

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('abreviated_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_chat_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institutions.institution')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='institutions.institution')),
                ('subjects', models.ManyToManyField(db_table='subject_groups_subjects', related_name='subject_groups', to='academics.subject')),
            ],
            options={
                'db_table': 'subject_groups',
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['institution'], name='idx_subjects_institution'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(models.F('institution'), django.db.models.functions.text.Lower('code'), name='index_subjects_on_institution_id_and_code'),
        ),
        migrations.AddConstraint(
            model_name='subjectgroup',
            constraint=models.UniqueConstraint(models.F('institution'), django.db.models.functions.text.Lower('name'), name='index_subject_groups_on_institution_id_and_name'),
        ),
    ]
