# Generated by Django 5.1.4 on 2026-04-17 02:21

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_student_groups', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='institutions.institution')),
                ('students', models.ManyToManyField(db_table='student_groups_students', related_name='student_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_groups',
            },
        ),
        migrations.CreateModel(
            name='StudentGroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_student_group_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_student_group_invitations', to=settings.AUTH_USER_MODEL)),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group_invitations', to='groups.studentgroup')),
            ],
            options={
                'db_table': 'student_group_invitations',
            },
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['institution', 'creator_student'], name='idx_stg_inst_creator'),
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(models.F('institution'), django.db.models.functions.text.Lower('name'), name='index_student_groups_on_institution_id_and_name'),
        ),
        migrations.AddIndex(
            model_name='studentgroupinvitation',
            index=models.Index(fields=['invitee'], name='idx_sgi_invitee'),
        ),
        migrations.AddIndex(
            model_name='studentgroupinvitation',
            index=models.Index(fields=['inviter'], name='idx_sgi_inviter'),
        ),
        migrations.AddIndex(
            model_name='studentgroupinvitation',
            index=models.Index(fields=['student_group'], name='idx_sgi_group'),
        ),
        migrations.AddConstraint(
            model_name='studentgroupinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student_group', 'invitee'), name='idx_student_group_invitations_pending_unique'),
        ),
    ]
