# Generated by Django 5.1.4 on 2026-04-17 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reunions', to=settings.AUTH_USER_MODEL)),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions', to='groups.studentgroup')),
                ('students', models.ManyToManyField(db_table='reunions_students', related_name='reunions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='academics.subject')),
            ],
            options={
                'db_table': 'reunions',
            },
        ),
        migrations.CreateModel(
            name='ReunionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunion_messages', to='reunions.reunion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunion_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reunion_messages',
            },
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['scheduled_for'], name='idx_reunions_scheduled_for'),
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['subject'], name='idx_reunions_subject'),
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['creator_student'], name='idx_reunions_creator'),
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['student_group'], name='idx_reunions_group'),
        ),
        migrations.AddIndex(
            model_name='reunionmessage',
            index=models.Index(fields=['reunion'], name='idx_rm_reunion'),
        ),
        migrations.AddIndex(
            model_name='reunionmessage',
            index=models.Index(fields=['student'], name='idx_rm_student'),
        ),
        migrations.AddIndex(
            model_name='reunionmessage',
            index=models.Index(fields=['created_at'], name='idx_rm_created_at'),
        ),
    ]
