# Generated by Django 5.1.4 on 2026-04-17 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=5000)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'In progress'), (2, 'Resolved')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'issue_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter'], name='idx_ir_reporter'), models.Index(fields=['status'], name='idx_ir_status')],
            },
        ),
        migrations.CreateModel(
            name='NewsletterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('news', 'News'), ('article', 'Article')], default='news', max_length=20)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newsletter_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'newsletter_entries',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['author'], name='idx_ne_author'), models.Index(fields=['published_at'], name='idx_ne_published_at'), models.Index(fields=['entry_type', 'published_at'], name='idx_ne_type_pub')],
            },
        ),
    ]
