# Generated by Django 5.1.4 on 2026-04-17 21:34

import apps.community.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.community.models._issue_report_image_path, validators=[apps.community.models.validate_image_size, apps.community.models.validate_image_content_type])),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.issuereport')),
            ],
            options={
                'db_table': 'issue_report_images',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['issue_report'], name='idx_iri_report')],
            },
        ),
    ]
